// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ToDo.Entity
{
    public partial class Task
    {
        [Key]
        public Guid TaskId { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [StringLength(200)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime PlanTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Deadline { get; set; }
        public bool IsImportant { get; set; }
        public bool IsFinish { get; set; }
    }
}