// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Performance.Entity
{
    [Table("Achievement")]
    public partial class Achievement
    {
        [Key]
        public Guid AchievementId { get; set; }
        /// <summary>
        /// 指标
        /// </summary>
        public Guid IndexLibraryId { get; set; }
        /// <summary>
        /// 机构/部门
        /// </summary>
        public Guid OrganizationId { get; set; }
        /// <summary>
        /// 年份
        /// </summary>
        public int Year { get; set; }
        /// <summary>
        /// 目标值
        /// </summary>
        [Column(TypeName = "decimal(18, 2)")]
        public decimal TargetValue { get; set; }
        /// <summary>
        /// 实际值
        /// </summary>
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ActualValue { get; set; }
        /// <summary>
        /// 保障值
        /// </summary>
        [Column(TypeName = "decimal(18, 2)")]
        public decimal GuaranteedValue { get; set; }
        /// <summary>
        /// 挑战值
        /// </summary>
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ChallengeValue { get; set; }

        [ForeignKey(nameof(IndexLibraryId))]
        [InverseProperty("Achievements")]
        public virtual IndexLibrary IndexLibrary { get; set; }
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("Achievements")]
        public virtual Organization Organization { get; set; }
    }
}