// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Performance.Entity
{
    [Table("IndexLibrary")]
    public partial class IndexLibrary
    {
        public IndexLibrary()
        {
            Achievements = new HashSet<Achievement>();
            OrganizationIndices = new HashSet<OrganizationIndex>();
        }

        /// <summary>
        /// 指标
        /// </summary>
        [Key]
        public Guid IndexLibraryId { get; set; }
        /// <summary>
        /// 指标名称
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        /// <summary>
        /// 指标范围
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Scope { get; set; }
        /// <summary>
        /// 指标类别
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Type { get; set; }
        /// <summary>
        /// 单位
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Unit { get; set; }
        /// <summary>
        /// 指标定义
        /// </summary>
        [Required]
        [StringLength(100)]
        public string Definition { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [StringLength(100)]
        public string Remark { get; set; }
        /// <summary>
        /// 是否启用
        /// </summary>
        public bool IsEnabled { get; set; }

        [InverseProperty(nameof(Achievement.IndexLibrary))]
        public virtual ICollection<Achievement> Achievements { get; set; }
        [InverseProperty(nameof(OrganizationIndex.IndexLibrary))]
        public virtual ICollection<OrganizationIndex> OrganizationIndices { get; set; }
    }
}