// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Performance.Entity
{
    [Table("OrganizationIndex")]
    public partial class OrganizationIndex
    {
        /// <summary>
        /// 部门绑定指标
        /// </summary>
        [Key]
        public Guid OrganizationIndexId { get; set; }
        /// <summary>
        /// 机构/部门
        /// </summary>
        public Guid OrganizationId { get; set; }
        /// <summary>
        /// 指标
        /// </summary>
        public Guid IndexLibraryId { get; set; }

        [ForeignKey(nameof(IndexLibraryId))]
        [InverseProperty("OrganizationIndices")]
        public virtual IndexLibrary IndexLibrary { get; set; }
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("OrganizationIndices")]
        public virtual Organization Organization { get; set; }
    }
}